name: circular_progress_button
description: A Flutter package providing a customizable circular progress button that fills in three steps.
homepage: https://github.com/yourusername/circular_progress_button
version: 0.0.1

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
